version: "3.7"

services:
  proxy:
    restart: unless-stopped
    environment:
      - ACME_AGREE=true
    ports:
      - 80:80
      - 443:443
  mysql:
    restart: unless-stopped

  app:
    restart: unless-stopped
    environment:
      ENV_MODE: production
    build:
      args:
        - ENV_MODE=production
    command: bash -c "yarn start"
